version: '3'
services:
  frontend:
    build: 
      context: .
      dockerfile: frontend.Dockerfile
    container_name: donation-web-frontend
    ports:
      - 21000:80
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: donation-web-backend
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - ADMIN_ACCOUNT=${ADMIN_ACCOUNT}
    working_dir: /root/backend
    command: gunicorn -c config.py wsgi:app
    # command: bash
    # stdin_open: true
    # tty: true
    volumes:
      - /home/kaminyou:/home/kaminyou
    depends_on:
      - db
  db:
    image: mysql:8
    container_name: donation-web-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 23000:3306
    volumes:
      - ./backend/sql:/docker-entrypoint-initdb.d
